# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2822037305176047a9e42f70c3ced17e46a25d8f03d88ae05d46481a5d27b56bb0012ffb503e197c656851aa5c3c7337d77e4799202a87bc67ab69d14cb32570

test:
  secret_key_base: bc1eb5f6a10e7a98798be578b46cb482f2bdcc4ca391abe11743f9b4efd36554facce4df62c89bf27f99da6a03bbaf92c6d14d6559c75840e6ac723dc9ab40ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
